name = "xterminal"
license = "MIT"
licenselink = "https://github.com/ArjunHaritsa/hugo-xterminal/blob/main/LICENSE.md"
description = "A fork and a mod of hugo-theme-re-terminal" 
tags = [
  "blog",
  "clean",
  "customizable",
  "dark",
  "highlighting",
  "minimal",
  "monotone",
  "multilingual",
  "personal",
  "responsive",
  "simple",
  "technical",
  "retro",
]
features = ["blog", "shortcode", "syntax highlighting"]
min_version = 0.128

[author]
name = "Arjun Haritsa"

[original]
name = "Mirus"
repo = "https://github.com/mirus-ua/hugo-theme-reterminal"
